version: '3.9'
services:
  server:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=guille
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongo-data:/data/db #Ruta donde se guardan los datos de mongo
      # mysql ->/var/lib/mysql es donde se guardan los datos
      # postgres ->/var/lib/postgresql/data es donde se guardan los datos
volumes:
  mongo-data:
